### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by DemOnJR** [igor-ruivo/generic-auto-updater#1]
I get this error when the auto updater is running: 
![tFpmlGV](https://user-images.githubusercontent.com/6385558/87337862-72a3b200-c544-11ea-9a11-62fac4543b60.png)

This is the main url: http://pipiasibogdan.ovh/patchlist.txt

**Comment by igor-ruivo** [comment]
Interesting. For some reason I'm getting Http error 403 (forbidden) when accessing your patchlist.txt through the app, but in the browser everything's ok.
I'll look into it.. Thanks for the feedback :)

**Comment by DemOnJR** [comment]
> Interesting. For some reason I'm getting Http error 403 (forbidden) when accessing your patchlist.txt through the app, but in the browser everything's ok.
> I'll look into it.. Thanks for the feedback :)

Thanks but the structure of patchlist.txt is ok how i write it?
I'm waiting for an solution of the 403 error, Thanks.

**Comment by igor-ruivo** [comment]
Yes, your patchlist.txt looks nice. It has some invisible characters tho, but that's ok. The engine trims them off.
I hope the latest commit fixes everything. Go check it out :)

**Comment by igor-ruivo** [comment]
> > Interesting. For some reason I'm getting Http error 403 (forbidden) when accessing your patchlist.txt through the app, but in the browser everything's ok.
> > I'll look into it.. Thanks for the feedback :)
> 
> Thanks but the structure of patchlist.txt is ok how i write it?
> I'm waiting for an solution of the 403 error, Thanks.

Yes, your patchlist.txt looks nice. It has some invisible characters tho, but that's ok. The engine trims them off.
I hope the latest commit fixes everything. Go check it out :)
