### ISSUE TITLE
Security Question

### ISSUE THREAD

**Issue by DemOnJR** [igor-ruivo/generic-auto-updater#3]
Is not more secured if you use sha3-512 instead of md5?
Here is the article https://en.wikipedia.org/wiki/Template:Comparison_of_SHA_functions

**Comment by igor-ruivo** [comment]
Yes. That is a trade-off that i leave for the ones who use this as a template to decide. If you prefer a faster hash but not so safe, use Md5 for instance. If you want something more secure, try to implement it in a class yourself. Make sure to implement the interface IHasher!

**Comment by DemOnJR** [comment]
ok, thanks.
