### ISSUE TITLE
Unable to find Webserver

### ISSUE THREAD

**Issue by isidorabendroth** [igor-ruivo/generic-auto-updater#5]
Also getting hung up with an unable to find webserver issue even though the .txt file is accessible via web-browser.

**Comment by igor-ruivo** [comment]
Hi,
Deleting all the content of the method static void SetupDefaultHeaders() from the class HttpClientDownloader.cs should do it. Thanks for reporting :) I'll put this info in readme, in case others feel the need to config their default headers, respecting their server's config.

**Comment by jbrud5** [comment]
Hi 
I still have the same issue event after removing SetupDefaultHeaders() content. 
I tried to host Metadata.txt file on a localhost and on server, same with app files. 

Actually Updater downloads well the first file but retry 3 times (as it sets by default) to download it and then stop with  error message "Couldn't connect to the Auto-Updater server. Please check if the website is online or check your internet connection."
And I can run it more and more, it still download the first missing file. 

Do you have any idea ? 
thx !
