### ISSUE TITLE
Hash generator

### ISSUE THREAD

**Issue by rjclarkewp007** [igor-ruivo/generic-auto-updater#6]
Hi

Sorry this might be a very dumb question, but i've never played around with Md5 or hashes whatever its called.
What can i use to generator that txt file with the files names and hashes so that it looks like your example?

like:
filename1
hash
filename2
hash

and also files that are in directories
like:
/folder/filename1
hash

thanks for the awesome updater and any help will be much appreciated!

**Comment by rjclarkewp007** [comment]
Ah I made a little powershell script which works great. :)

**Comment by jbrud5** [comment]
> Ah I made a little powershell script which works great. :)

Hi !

I have the same "issue" than you. Could you share your powershell script ? I do not really know it.

**Comment by igor-ruivo** [comment]
Hey!
You can use the Hash/Md5Hasher.cs class and use the MD5 interface and choose an appropriate method to get the MD5 hash from a file in the disk.

Use it in everyfile you want, to retrieve the hashes
