### ISSUE TITLE
Malicious file

### ISSUE THREAD

**Issue by rjclarkewp007** [igor-ruivo/generic-auto-updater#8]
Sadly this cannot really be used because Windows defender and many other anti virus programs see this as malware and will remove / block it. :(

You can build the solution and upload it to VirusTotal to see how many anti virus programs see this as malicious.
I use Eset Nod32 and it did not have a problem with the file, but once i started to send it to others the program was blocked everywhere even Google blocked it on my Drive.

**Comment by EasyMochi** [comment]
Same here

**Comment by igor-ruivo** [comment]
Either sign the exe file or contact the antivirus companies to report the false positive
